apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-mbpyriyr
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-mbpyriyr:f2af5b0e5fb104b5e5e3a2390e3d65b0c8c05f71@sha256:0538b26d6707d2a51310a5b28236742cf730f9312c1241b003ecce1c116241aa
          name: container-image
